server:
  port: 8080
  servlet:
    context-path: /inetum/cop  

spring:
  datasource:
    url: jdbc:mysql://localhost:33060/db
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none